# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: Bash@3
  inputs:
    script:  echo 'Hello world'
- task: DotNetCoreCLI@2
  displayName: Run unit tests
  inputs:
    command: 'test'
    projects: '**/*UnitTests.csproj'
    testRunTitle: 'Weather Forecast Unit Tests'
