# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

name: Echo Pipeline

trigger:
  branches:
   include:
     - main
  paths:
    exclude:
    - azure-pipelines.yml

pool:
  vmImage: ubuntu-18.04

stages:
- stage: Build
  jobs:
  - job: BuildJob
    steps:
    - script: echo Building!
- stage: Test
  jobs:
  - job: TestOnWindows
    steps:
    - script: echo Testing on Windows!
  - job: TestOnLinux
    steps:
    - script: echo Testing on Linux!
- stage: DevEnv
  jobs:
  - deployment: DeployAppDev
    environment: 'kehitys'
    strategy:
      runOnce:
        deploy:
          steps:
          - script: echo Hello DEV!
- stage: TestEnv
  jobs:
  - deployment: DeployAppTest
    environment: 'testi'
    strategy:
      runOnce:
        deploy:
          steps:
          - script: echo Hello TESTI!
