# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

name: FOO

trigger:
- main

variables:
  buildConfiguration: 'Release'

pool:
  vmImage: ubuntu-20.04

steps:

- task: DotNetCoreCLI@2
  displayName: dotnet test
  inputs:
    command: 'test'
    projects: '**/*UnitTests.csproj'
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: dotnet publish
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: '**/AzDevOpsDemoWebApplication.csproj'
    arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)/build'

- task: DotNetCoreCLI@2
  displayName: dotnet publish integration tests
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: '**/IntegrationTests.csproj'
    arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)/integration_tests'

- task: PublishBuildArtifacts@1
  displayName: Publish Build Artifact - The Build
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/build'
    ArtifactName: 'build'
    publishLocation: 'Container'

- task: PublishBuildArtifacts@1
  displayName: Publish Build Artifact - The Integration Tests
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/integration_tests'
    ArtifactName: 'integration_tests'
    publishLocation: 'Container'